    version: '3'

    services:

      app:
        build:
          context: .
          dockerfile: containers/development/Dockerfile
        image: aerostat:app
        command: containers/development/bootstrap.sh
        ports:
          - 3000:3000
        volumes:
          - .:/app
          - gems:/gems
        depends_on:
          - db
        environment:
          - DOCKERIZED=1

      db:
        image: postgres:9.6
        ports:
          - '15432:5432'
        volumes:
          - db_volume:/var/lib/postgresql/data

    volumes:
      db_volume:
      gems:
